---
title: "Mexican Audits"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(tidyverse)
library(stringr)
library(janitor)
library(magrittr)
library(reshape2)
```


```{r data}

data <- readRDS("mexican_audits.rds")

```

First extract the amount of pesos lost in each audit, and remove the values of that are NA. Second, add up the amount lost in each audit. Lastly, mutate this into a separate column to be used for data analysis.


```{r data cleaning}
data <- clean_names(data)
options("scipen"=100, "digits"=4)

df_con_extraccion <- data %>% dplyr::mutate(
  loss = stringr::str_extract_all(data$texto_accion, "[0-9,.]+(?= pesos)")
  ) %>%
  tidyr::unnest() %>%
  dplyr::mutate(
    loss =
      stringr::str_replace(loss, ",","") 
      )

df_con_extraccion$loss <- as.numeric(gsub(",", "", df_con_extraccion$loss, fixed = TRUE))
df_con_extraccion$loss[is.na(df_con_extraccion$loss)] <- 0
df_con_extraccion$clave_accion <- as.character(df_con_extraccion$clave_accion)
df_con_extraccion <- df_con_extraccion %>% group_by(clave_accion) %>% mutate(id = 1:n())



#Here we are checking to see if any one value is equal to half the sum of the other values. 
#We're doing this to make sure that there are no duplicate values 
        df_wide <- dcast(df_con_extraccion, clave_accion ~ id, value.var = "loss")
        df_wide[is.na(df_wide)] <- 0
        df_wide <-clean_names(df_wide)
        df_wide$check <- rowSums(df_wide[,2:27])
        
                for (i in 1:length(df_wide$x1)){
                           if(df_wide$x1[i] == df_wide$check[i]/2){        
                                    df_wide$x1[i] <- 0 
                                    
                           } else if (df_wide$x2[i] == df_wide$check[i]/2){        
                                    df_wide$x2[i] <- 0  
                                    
                           }else if (df_wide$x3[i] == df_wide$check[i]/2){        
                                    df_wide$x3[i] <- 0   
                                    
                           }else if (df_wide$x4[i] == df_wide$check[i]/2){        
                                    df_wide$x4[i] <- 0  
                                    
                           }else if (df_wide$x5[i] == df_wide$check[i]/2){        
                                    df_wide$x5[i] <- 0  
                                    
                           }else if (df_wide$x6[i] == df_wide$check[i]/2){        
                                    df_wide$x6[i] <- 0  
                                    
                           }else if (df_wide$x7[i] == df_wide$check[i]/2){        
                                    df_wide$x7[i] <- 0  
                                    
                           }else if (df_wide$x8[i] == df_wide$check[i]/2){        
                                    df_wide$x8[i] <- 0  
                                    
                           }else if (df_wide$x9[i] == df_wide$check[i]/2){        
                                    df_wide$x9[i] <- 0  
                                    
                           }else if (df_wide$x10[i] == df_wide$check[i]/2){        
                                    df_wide$x10[i] <- 0  
                                    
                           }else if (df_wide$x11[i] == df_wide$check[i]/2){        
                                    df_wide$x11[i] <- 0  
                                    
                           }else if (df_wide$x12[i] == df_wide$check[i]/2){        
                                    df_wide$x12[i] <- 0   
                                    
                           }else if (df_wide$x13[i] == df_wide$check[i]/2){        
                                    df_wide$x13[i] <- 0     
                                    
                           }else if (df_wide$x14[i] == df_wide$check[i]/2){        
                                    df_wide$x14[i] <- 0   
                                    
                           }else if (df_wide$x15[i] == df_wide$check[i]/2){        
                                    df_wide$x15[i] <- 0      
                                    
                           }else if (df_wide$x16[i] == df_wide$check[i]/2){        
                                    df_wide$x16[i] <- 0     
                                    
                           }else if (df_wide$x17[i] == df_wide$check[i]/2){        
                                    df_wide$x17[i] <- 0    
                                    
                           }else if (df_wide$x18[i] == df_wide$check[i]/2){        
                                    df_wide$x18[i] <- 0     
                                    
                           }else if (df_wide$x19[i] == df_wide$check[i]/2){        
                                    df_wide$x19[i] <- 0     
                                    
                           }else if (df_wide$x20[i] == df_wide$check[i]/2){        
                                    df_wide$x20[i] <- 0      
                                    
                           }else if (df_wide$x21[i] == df_wide$check[i]/2){        
                                    df_wide$x21[i] <- 0      
                                    
                           }else if (df_wide$x22[i] == df_wide$check[i]/2){        
                                    df_wide$x22[i] <- 0    
                                    
                           }else if (df_wide$x23[i] == df_wide$check[i]/2){        
                                    df_wide$x23[i] <- 0     
                                    
                           }else if (df_wide$x24[i] == df_wide$check[i]/2){        
                                    df_wide$x24[i] <- 0     
                                    
                           }else if (df_wide$x25[i] == df_wide$check[i]/2){        
                                    df_wide$x25[i] <- 0      
                                    
                           }else if (df_wide$x26[i] == df_wide$check[i]/2){        
                                    df_wide$x26[i] <- 0    
                                    
                           }
                }



df_wide$total_loss <- rowSums( df_wide[,2:27])
loss_per_audit <- select(df_wide, clave_accion, total_loss)


data_with_loss <- left_join(data, loss_per_audit, by = "clave_accion")
data_with_loss$total_loss[is.na(data_with_loss$total_loss)] <- 0


saveRDS(data_with_loss,"mexican_audits_with_loss.rds")



```

```{r, mapping}
 data <- readRDS("mexican_audits_with_loss.rds")
options(scipen=999)

data$total_loss[is.na(data$total_loss)] <- 0
data <- filter(data, !entidad_federativa %in% c("", "-"))

bystate <- data %>% group_by(entidad_federativa,x_u_feff_ano_cuenta_publica) %>%  summarize(loss_by_state = sum(total_loss))

bystate2018 <- filter(bystate, x_u_feff_ano_cuenta_publica == "2018")
bystate2018$entidad_federativa <- as.character(bystate2018$entidad_federativa)
bystate2018$entidad_federativa <- gsub("Ciudad de México", "Distrito Federal",bystate2018$entidad_federativa , fixed = TRUE)

if (!require("devtools")) {
    install.packages("devtools")
}
devtools::install_github("diegovalle/mxmaps")

data(df_mxstate)
df_mxstate$value <- df_mxstate$pop

df_mxstate <- left_join(df_mxstate,bystate2018, by = c("state_name_official"="entidad_federativa"))

df_mxstate <- mutate(df_mxstate, loss_per_person = loss_by_state/pop)

df_mxstate$value <- df_mxstate$loss_per_person

mxstate_choropleth(df_mxstate,num_colors = 8,
                   title = "Loss of funds person in 2018, by state") 

```

```{r}
data(df_mxstate)


df_mxstate2 <- left_join(df_mxstate,bystate2018, by = c("state_name_official"="entidad_federativa"))

df_mxstate2$value <- df_mxstate2$loss_by_state

mxstate_choropleth(df_mxstate2,num_colors =8,
                   title = "Total loss of funds, by state")
```

```{r, municipalities}

```